vega:
  url: http://10.3.70.145:30739/

oss:
  endpoint: https://smartvision-aipc-open.oss-cn-hangzhou.aliyuncs.com

registry:
  npm: https://registry.npmmirror.com
  pip: http://mirrors.aliyun.com/pypi/simple/