vega:
  url: http://8.136.116.36:31251/

oss:
  endpoint: https://smartvision-aipc-open.oss-cn-hangzhou.aliyuncs.com
  icon: https://smartvision-aipc-open.oss-cn-hangzhou.aliyuncs.com/oadin/icon/

registry:
  npm: https://registry.npmmirror.com
  pip: http://mirrors.aliyun.com/pypi/simple/