export const mcpListDataMock = [
  {
    id: 1,
    name: { src: '图像去雾增强', zh: '图像去雾增强' },
    abstract: { src: '该 MCP 实现了图像去雾和增强的组合处理流程', zh: '该 MCP 实现了图像去雾和增强的组合处理流程' },
    supplier: 'aliyun',
    logo: 'https://example.png',
    popularity: 8615,
    tags: ['图像', '增强'],
    hosted: true,
    updatedAt: 1747234202,
  },
  {
    id: 2,
    name: { src: 'AI 图像压缩', zh: 'AI 图像压缩' },
    abstract: { src: '智能压缩图像的高效解决方案', zh: '智能压缩图像的高效解决方案' },
    supplier: 'aliyun',
    logo: 'https://example.png',
    popularity: 8615,
    tags: ['图像', '压缩'],
    hosted: true,
    updatedAt: 1747234202,
  },
  {
    id: 3,
    name: { src: '视频质量分析', zh: '视频质量分析' },
    abstract: { src: '基于 AI 的视频画质评估与优化方案', zh: '基于 AI 的视频画质评估与优化方案' },
    supplier: 'aliyun',
    logo: 'https://example.png',
    popularity: 9240,
    tags: ['视频', 'AI'],
    hosted: true,
    updatedAt: 1747234202,
  },
  {
    id: 4,
    name: { src: '人脸检测服务', zh: '人脸检测服务' },
    abstract: { src: '快速定位图像中的人脸区域并进行属性分析', zh: '快速定位图像中的人脸区域并进行属性分析' },
    supplier: 'aliyun',
    logo: 'https://example.png',
    popularity: 10345,
    tags: ['人脸', '检测'],
    hosted: true,
    updatedAt: 1747234202,
  },
  {
    id: 5,
    name: { src: '语音识别转文字', zh: '语音识别转文字' },
    abstract: { src: '将音频流转换为可编辑文本内容', zh: '将音频流转换为可编辑文本内容' },
    supplier: 'aliyun',
    logo: 'https://example.png',
    popularity: 11200,
    tags: ['语音', '识别'],
    hosted: true,
    updatedAt: 1747234202,
  },
  // 省略中间的数据以保持简洁
  {
    id: 30,
    name: { src: '文档格式转换', zh: '文档格式转换' },
    abstract: { src: '实现 PDF、Word、Excel 等文档格式之间的互转', zh: '实现 PDF、Word、Excel 等文档格式之间的互转' },
    supplier: 'aliyun',
    logo: 'https://example.png',
    popularity: 8750,
    tags: ['文档', '转换'],
    hosted: true,
    updatedAt: 1747234202,
  },
];
