import { IMcpListItem } from '@/types/model.ts';

export const availableMcps: IMcpListItem[] = [
  {
    id: '683ec88241fa614eb15323b9',
    name: {
      src: 'Jina-AI-MCP-Tools',
      zh: 'Jina-AI-MCP-Tools',
    },
    abstract: {
      src: 'A Model Context Protocol (MCP) server that integrates with Jina AI Search Foundation APIs.',
      zh: '一个与 Jina AI 搜索基础 API 集成的 模型上下文协议（MCP）服务器。',
    },
    supplier: 'PsychArch',
    logo: 'https://resources.modelscope.cn/mcp-server-cover/3981b5de-be7a-4134-9ced-488018601ebc.png',
    popularity: 44,
    tags: [],
    hosted: true,
    status: 0,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747836466,
  },
  {
    id: '683ec88241fa614eb1532449',
    name: {
      src: 'MCP-Advisor',
      zh: 'MCP-Advisor',
    },
    abstract: {
      src: 'MCP Advisor is a discovery and recommendation service that helps AI assistants explore Model Context Protocol (MCP) servers using natural language queries. It makes it easier for users to find and leverage MCP tools suitable for specific tasks.',
      zh: 'MCP Advisor 是一个发现和推荐服务，帮助 AI 助手使用自然语言查询探索 Model Context Protocol (MCP) 服务器。它让用户更容易找到并利用适合特定任务的 MCP 工具。',
    },
    supplier: 'istarwyh',
    logo: '',
    popularity: 35,
    tags: [],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829990,
  },
  {
    id: '683ec88241fa614eb1531fc5',
    name: {
      src: 'mcp-server-alipay',
      zh: '支付宝MCP',
    },
    abstract: {
      src: '@alipay/mcp-server-alipay 是支付宝开放平台提供的 MCP Server，让你可以轻松将支付宝开放平台提供的交易创建、查询、退款等能力集成到你的 LLM 应用中，并进一步创建具备支付能力的智能工具。',
      zh: '是支付宝开放平台提供的 MCP Server，让你可以轻松将支付宝开放平台提供的交易创建、查询、退款等能力集成到你的 LLM 应用中，并进一步创建具备支付能力的智能工具。',
    },
    supplier: 'alipay',
    logo: 'https://resources.modelscope.cn/studio-cover-prod/studio-cover_86796236-c604-4a77-bfa4-e9ca2ca93297.png',
    popularity: 24900,
    tags: ['支付工具'],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829985,
  },
  {
    id: '683ec88241fa614eb1531fd6',
    name: {
      src: 'leetcode-mcp-server',
      zh: 'LeetCode(力扣)',
    },
    abstract: {
      src: 'LeetCode MCP server implementation for LeetCode API integration, enabling automated access to programming problems, user data, and contest information.',
      zh: 'MCP 服务器实现 LeetCode API 集成，支持自动化获取编程题库、用户数据和竞赛信息。',
    },
    supplier: 'jinzcdev',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_402ed2b0-a575-4187-813f-ae82d89af6a1.png',
    popularity: 6685,
    tags: ['知识搜索'],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829983,
  },
  {
    id: '683ec88241fa614eb1531fc7',
    name: {
      src: 'bing-cn-mcp-server',
      zh: '必应搜索中文',
    },
    abstract: {
      src: 'Bing search Chinese',
      zh: '必应搜索中文',
    },
    supplier: 'yan5236',
    logo: 'https://resouces.modelscope.cn/studio-cover-prod/studio-cover_c1a4feec-7dd2-4188-bd72-aebde64758f3.png',
    popularity: 11337,
    tags: ['搜索服务'],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829976,
  },
  {
    id: '683ec88241fa614eb1531fc4',
    name: {
      src: 'amap-maps',
      zh: '高德地图',
    },
    abstract: {
      src: 'Amap Maps is a server that supports any MCP protocol client, allowing users to easily utilize the Amap Maps MCP server for various location-based services.',
      zh: '高德地图是一个支持任何MCP协议客户端的服务器，允许用户轻松利用高德地图MCP服务器获取各种基于位置的服务。',
    },
    supplier: 'amap',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_982efeea-b6fe-4c38-91da-501de5a7f098.png',
    popularity: 43332,
    tags: ['地图服务'],
    hosted: true,
    status: 1,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747829974,
  },
  {
    id: '683ec88241fa614eb1531fc3',
    name: {
      src: 'fetch',
      zh: 'Fetch网页内容抓取',
    },
    abstract: {
      src: 'This server enables LLMs to retrieve and process content from web pages, converting HTML to markdown for easier consumption.',
      zh: '该服务器使大型语言模型能够检索和处理网页内容，将HTML转换为markdown格式，以便于更轻松地使用。',
    },
    supplier: 'modelcontextprotocol',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_761f7bfe-fc5c-4753-b955-dcdd3288941b.png',
    popularity: 69492,
    tags: ['网页抓取'],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829971,
  },
  {
    id: '683ec88241fa614eb1532098',
    name: {
      src: 'sentry',
      zh: 'Sentry监控工具',
    },
    abstract: {
      src: 'This server provides tools to inspect error reports, stacktraces, and other debugging information from your Sentry account.',
      zh: '此服务器提供了用于查看来自您的 Sentry 账户的错误报告、堆栈跟踪和其他调试信息的工具。',
    },
    supplier: 'modelcontextprotocol',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_c1f05f51-704c-45c2-8091-444c8149c912.png',
    popularity: 360,
    tags: [],
    hosted: true,
    status: 0,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb153204d',
    name: {
      src: 'gdrive',
      zh: '谷歌云盘文件管理器',
    },
    abstract: {
      src: 'This MCP server integrates with Google Drive to allow listing, reading, and searching over files.',
      zh: '该MCP服务器与Google Drive集成，以允许列出、读取和搜索文件。',
    },
    supplier: 'modelcontextprotocol',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_bbbedf4b-06fa-4b63-a558-c00938e8ee65.png',
    popularity: 629,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb153203b',
    name: {
      src: 'mcp-server-neon',
      zh: 'Neon数据库',
    },
    abstract: {
      src: 'Lets you use Claude Desktop, or any MCP Client, to use natural language to accomplish things with [Neon](https://neon.tech/).',
      zh: '让你能够使用 Claude Desktop 或任何 MCP 客户端，通过自然语言来使用 [Neon](https://neon.tech/) 完成任务。',
    },
    supplier: 'neondatabase-labs',
    logo: 'https://resources.modelscope.cn/mcp-covers/avatar/neondatabase-labs.png',
    popularity: 715,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb1532034',
    name: {
      src: 'workers-mcp',
      zh: 'Cloudflare Workers MCP连接器',
    },
    abstract: {
      src: 'A package that connects Claude Desktop and other MCP clients to Cloudflare Workers, enabling custom functionality to be accessed via natural language through the Model Context Protocol.',
      zh: '一个将 Claude Desktop 和其他 MCP 客户端连接到 Cloudflare Workers 的软件包，通过模型上下文协议（Model Context Protocol）， enables 自定义功能可以通过自然语言访问。',
    },
    supplier: 'cloudflare',
    logo: 'https://resources.modelscope.cn/mcp-covers/avatar/cloudflare.png',
    popularity: 789,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb153202b',
    name: {
      src: 'ableton-mcp',
      zh: 'Ableton',
    },
    abstract: {
      src: 'Connects Ableton Live to Claude AI through the Model Context Protocol, enabling AI-assisted music production by allowing Claude to directly interact with and control Ableton Live sessions.',
      zh: '通过模型上下文协议将Ableton Live与Claude AI连接起来，通过允许Claude直接与Ableton Live会话交互和控制，实现人工智能辅助的音乐制作。',
    },
    supplier: 'ahujasid',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_4f162c8b-eb82-4634-9d86-61981b735e3c.jpg',
    popularity: 893,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829968,
  },
];
