import { IMcpListItem, IModelDataItem } from '@/types/model.ts';

export const availableModels: IModelDataItem[] = [
  {
    id: '40b25b4d-0a1e-408a-a066-656562333330323439663535',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'BAAI',
    method: '',
    desc: 'BGE-M3 是 BAAI 推出的一款新机型，以多功能、多语言和多粒度的多功能性而著称。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'bge-m3:567m',
    service_provider_name: 'local_ollama_embed',
    size: '1.2GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/BAAI.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: '790764642607',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '398c9e2c-2049-432e-a4d2-336434323037663434323635',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'codeQwen-7B 是aliyun通义千问团队推出的编程模型，约70亿参数，支持多语言编程，作为通义灵码的核心技术底座提供高效编程辅助‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'codeqwen:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.2GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: true,
    class: ['文本生成'],
    ollama_id: 'df352abf55b1',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'df7ac73f-b4b3-4a79-b27e-626235656530613563636263',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'deepscaler-1.5B 是基于 ‌Deepseek-R1-Distilled-Qwen-1.5B 通过强化学习微调优化的语言模型，约15亿参数，适用于轻量化设备部署与实时交互场景。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepscaler:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '3.6GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '0031bcf7459f',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'b27b54f2-914b-4357-9149-303033663639616266363837',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'Deepseek-coder-v2:16B 是深度求索推出的160亿参数‌代码大模型‌，支持338种编程语言‌的代码生成与理解任务‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-coder-v2:16b',
    service_provider_name: 'local_ollama_chat',
    size: '8.9GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '63fb193b3a9b',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '49321b3f-fceb-4c90-85fc-643563376131356439626463',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'Deepseek-llm-7B 是 Deepseek 团队开发的中文/多语言大模型，约70亿参数，在数学推理、代码生成等任务中表现优异‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-llm:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.0GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: true,
    class: ['文本生成'],
    ollama_id: '9aab369a853b',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '8370398b-5407-402f-a325-336631643637356231393937',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'Deepseek-r1-1.5B 是 Deepseek 团队研发的语言模型，约15亿参数，属于Deepseek-R1模型系列中的轻量级版本，适合基础任务和低资源环境。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-r1:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '1.1GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'a42b25d8c10a',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '81d25018-1657-46f4-8ceb-373164326466363934393536',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'Deepseek-r1-14B 是 Deepseek 团队研发的大规模语言模型，其参数量达到140亿。该模型在自然语言处理任务中表现出色，能够提供高质量的语言理解和生成能力。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-r1:14b',
    service_provider_name: 'local_ollama_chat',
    size: '9.0GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'ea35dfe18182',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'e11bc188-2882-4069-a7ce-316664653130336435353138',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'Deepseek-r1-7B 是一款 Deepseek 团队研发的模型，主要用于大模型推理场景，具有70亿参数，适用于多种应用场景。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-r1:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.7GB',
    is_recommended: true,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '0a8c26691023',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'cce2636f-f7ed-429e-9002-613165393436386336656136',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: '‌Deepseek-r1-8B‌是一款基于 Llama 架构的语言模型，拥有80亿的参数数量，经过深度蒸馏处理，使得模型在复杂的自然语言处理任务中表现出色，同时节省计算资源‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-r1:8b',
    service_provider_name: 'local_ollama_chat',
    size: '4.9GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '28f8fd6cdc67',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '584e8ed1-7412-4ff9-86d4-656330303138623739653336',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'deepseek',
    method: '',
    desc: 'Deepseek-v2:16B 是 Deepseek 团队开发的升级版大语言模型，约160亿参数，擅长代码生成、数学推理等任务‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: '',
    auth_fields: ['api_key'],
    name: 'deepseek-v2:16b',
    service_provider_name: 'local_ollama_chat',
    size: '8.9GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/deepseek.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '7c8c332f2df7',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '0ce77296-e636-4794-af32-613663656161343664383131',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'zhipuAi',
    method: '',
    desc: 'glm4:9B 是清华zhipuAi开源的90亿参数‌多模态对话模型‌,支持26种语言,具备代码执行、网页浏览及多模态交互能力‌。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'glm4:9b',
    service_provider_name: 'local_ollama_chat',
    size: '5.5GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/glm.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '5b699761eca5',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: true,
  },
  {
    id: 'd8c109c0-f063-48a5-9b4d-613139303566303732386335',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'IBM',
    method: '',
    desc: 'IBM Granite Embedding 278M 模型是纯文本密集双编码器嵌入模型,适用于多语言用例。这些模型旨在为给定的文本块生成固定长度的向量表示，可用于文本相似性、检索和搜索应用。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'granite-embedding:278m',
    service_provider_name: 'local_ollama_embed',
    size: '563MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/IBM.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: '1a37926bf842',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '0448c94a-5caa-4583-bef0-633735666539366164393339',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'Mixedbread',
    method: '',
    desc: 'mxbai-embed-large来自mixedbread.ai的最先进的大型嵌入模型，该模型在 MTEB 上实现了 Bert-large 规模模型的 SOTA 性能。其性能超越了 OpenAItext-embedding-3-large模型等商业模型，并与其 20 倍规模模型的性能相当,在没有 MTEB 数据重叠的情况下进行训练，这表明该模型在多个领域、任务和文本长度方面具有良好的泛化能力。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'mxbai-embed-large',
    service_provider_name: 'local_ollama_embed',
    size: '670MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/Mixedbread.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: '468836162de7',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '5106a180-2faa-4700-86d1-613631623633373561616566',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'Nomic',
    method: '',
    desc: 'nomic-embed-text是一个具有大型标记上下文窗口的高性能开放嵌入模型，也是一个基于 Sentence Transformers 库的句子嵌入模型，专门用于特征提取和句子相似度计算。在多个任务上表现出色，特别是在分类、检索和聚类任务中。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'nomic-embed-text',
    service_provider_name: 'local_ollama_embed',
    size: '274MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/Nomic.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: '0a109f422b47',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '5d204ef2-fc6a-4545-9c98-306139646136346637613561',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'BAAI',
    method: '',
    desc: 'bge-large可以将任何文本映射到低维密集向量，用于检索、分类、聚类或语义搜索等任务。它也可以用于 LLM 的向量数据库。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'quentinz/bge-base-zh-v1.5:f16',
    service_provider_name: 'local_ollama_embed',
    size: '205MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/BAAI.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: 'cd232613fa6f',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '87c0b009-2d93-4f00-9662-333037666261373163373263',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'BAAI',
    method: '',
    desc: 'bge-large可以将任何文本映射到低维密集向量，用于检索、分类、聚类或语义搜索等任务。它也可以用于 LLM 的向量数据库。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'quentinz/bge-large-zh-v1.5:f16',
    service_provider_name: 'local_ollama_embed',
    size: '671MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/BAAI.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: 'bc8ca0995fcd651',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '31ee3e7e-51a8-4a60-a20a-383131623536363061383533',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2-math-1.5B 是aliyun通义千问团队推出的数学与推理向第二代模型，约15亿参数，适用于多步逻辑推理与竞赛数学题求解‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2-math:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '935MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'a4fdda0c6cc5',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: true,
  },
  {
    id: '3421af88-f447-43f8-a7d3-356539626463303364616134',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2-math-7B 是aliyun通义千问团队推出的数学与推理向第二代模型，约70亿参数，擅长多步逻辑推理与竞赛数学题求解‌，支持中英双语数学问题解析‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2-math:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.4GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '28cc3a337734',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: true,
  },
  {
    id: 'c00cf249-3991-4cab-aa4f-623661656531643236373630',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-coder-0.5B 是aliyun通义千问团队推出的编程向第三代模型，约5亿参数，基于 Qwen2.5 架构‌与 Transformer 解码器‌设计，支持 Python 等92种编程语言。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5-coder:0.5b',
    service_provider_name: 'local_ollama_chat',
    size: '531MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'd392ed348d5b',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '0cfb19fa-2d26-4482-a2e6-306238393134366532333036',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-coder-1.5B 是aliyun通义千问团队推出的编程向第三代模型，约15亿参数，支持 92 种编程语言，针对轻量化设备提供高效代码生成、补全与修复能力。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5-coder:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '986MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '6d3abb8d2d53',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '187c6954-a781-4f8f-a4a2-383531646433623239343837',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-coder-14B 是aliyun通义千问团队推出的编程向第三代大模型，约140亿参数，支持 92 种编程语言，重点优化大型代码库协同开发与复杂逻辑推理能力。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5-coder:14b',
    service_provider_name: 'local_ollama_chat',
    size: '9.0GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '3028237cc8c5',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '0819f663-b588-47bc-bf1a-656266393731633932316266',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-coder-3B 是aliyun通义千问团队推出的编程向第三代模型，约30亿参数，基于 Qwen2.5 架构‌与 Transformer 解码器‌设计，重点增强多语言代码生成与优化能力，适用于中等复杂度编程任务。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5-coder:3b',
    service_provider_name: 'local_ollama_chat',
    size: '1.9GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'e7149271c296',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '54904615-fb6f-404e-8446-313064663266663633373663',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-coder-7B 是aliyun通义千问团队推出的编程向第三代模型，约70亿参数，支持 92 种编程语言，重点提升代码推理与修复能力，适用于复杂编程任务。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5-coder:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.7GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '2b0496514337',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '413583ae-d856-417d-9c8a-636665303365613262383430',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-0.5B 是aliyun通义千问团队推出的第三代小参数模型，约5亿参数，属于轻量级模型‌，提供代码生成、文本理解等核心能力，适合轻量级自然语言任务。‌',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5:0.5b',
    service_provider_name: 'local_ollama_chat',
    size: '398MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'a8b0c5157701',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '8fe5daf1-ba66-45de-a431-396463333637613730383364',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-1.5B 是aliyun通义千问团队推出的第三代轻量级模型，约15亿参数，在保持轻量化的同时，通过架构优化与数据扩展实现了与更大规模模型相近的推理能力。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '986MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '65ec06548149',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '8a5da271-8b27-4919-bb76-613938383630333061373964',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-14B 是aliyun通义千问团队推出的第三代大模型，约147亿参数，支持多语言，在数学推理、代码生成和多语言任务中表现卓越。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5:14b',
    service_provider_name: 'local_ollama_chat',
    size: '9.0GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '7cdf5a0187d5',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'f43f36c1-479a-4af7-89d6-363663353031373238306138',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-3B 是aliyun通义千问团队推出的第三代模型，约30亿参数，覆盖中文、英文、日文等 29 种语言，在保持端侧部署优势的同时，通过架构优化实现了与 7B 参数模型相近的任务处理能力‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5:3b',
    service_provider_name: 'local_ollama_chat',
    size: '1.9GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '357c53fb659c',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '76376bdc-004c-47d2-8d73-353934396164333833636331',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2.5-7B 是aliyun通义千问团队推出的第三代模型，约70亿参数，在长文本处理、多语言支持和专业领域任务中展现了与更大规模模型相近的性能，是平衡算力成本与任务精度的优选方案。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2.5:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.7GB',
    is_recommended: true,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '845dbda0ea48',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '95deb322-1756-453a-8d94-303161663535646363623732',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2-0.5B 是aliyun通义千问团队推出的第二代模型，约5亿参数，面向入门级应用和小型任务开发‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2:0.5b',
    service_provider_name: 'local_ollama_chat',
    size: '352MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '6f48b936a09f',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '155e7f18-81a0-4467-b904-623962333138626537363966',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2-1.5B 是aliyun通义千问团队推出的第二代模型，约15亿参数，擅长文本分类、数学推理等任务‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '935MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'f6daf2b25194',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'f5a3eec7-7cbf-4ee8-965c-626636383239376166306533',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen2-7B 是aliyun通义千问团队推出的第二代模型，约70亿参数，支持 ‌27 种语言。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen2:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.4GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'dd314f039b9d',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'f0a80611-1cee-458b-84e4-356132313463393138356638',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen-0.5B 是aliyun通义千问团队推出的轻量级模型，约5亿参数，专为低成本部署设计，适用于入门级AI应用场景‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen:0.5b',
    service_provider_name: 'local_ollama_chat',
    size: '395MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'b5dc5e784f2a',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '007205d8-7c85-4a61-ac09-386366653639343665376434',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen-1.8B 是aliyun通义千问团队推出的模型，约18亿参数，具备多语言处理能力‌与‌稀疏注意力机制‌‌，适用于轻量化场景下的文本生成、问答等任务‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen:1.8b',
    service_provider_name: 'local_ollama_chat',
    size: '1.1GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'b6e8ec2e7126',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '12dd9b46-a18b-43ba-a87f-316261316336636466356233',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen-4B 是aliyun通义千问团队推出的模型，约40亿参数，支持多语言，适用于本地化代码生成、文档分析等中等负载场景‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen:4b',
    service_provider_name: 'local_ollama_chat',
    size: '2.3GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: 'd53d04290064',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: '150fc9f8-73c0-44f8-a00b-363865643336653338383462',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'aliyun',
    method: '',
    desc: 'Qwen-7B 是aliyun通义千问团队推出的模型，约70亿参数，适用于文本生成、智能问答及本地化知识库构建等中高负载场景‌。',
    url: '',
    auth_type: 'apikey',
    auth_apply_url: 'https://help.aliyun.com/zh/model-studio/developer-reference/get-api-key?spm=a2c4g.11186623.0.0.110f4d4dZvW4Ml',
    auth_fields: ['api_key'],
    name: 'qwen:7b',
    service_provider_name: 'local_ollama_chat',
    size: '4.5GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/qwen.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '2091ee8c8d8f',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'fb6c6f6d-b707-4012-9f43-353463643533313165616636',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'Snowflake',
    method: '',
    desc: 'snowflake-arctic-embed是一套文本嵌入模型，专注于创建针对性能优化的高质量检索模型。\n\n这些模型利用现有的开源文本表示模型（例如 bert-base-uncased）进行训练，并在多阶段流水线中进行训练以优化其检索性能。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'snowflake-arctic-embed',
    service_provider_name: 'local_ollama_embed',
    size: '669MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/Snowflake.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: '21ab8b9b0545',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'fc047dcd-78fd-49c9-b33c-616264326336376333653936',
    service_name: 'embed',
    api_flavor: 'ollama',
    flavor: 'Snowflake',
    method: '',
    desc: 'Snowflake 的前沿嵌入模型。Arctic Embed 2.0 增加了多语言支持，同时又不牺牲英语的性能或可扩展性。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'snowflake-arctic-embed2',
    service_provider_name: 'local_ollama_embed',
    size: '1.2GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/Snowflake.png',
    can_select: false,
    class: ['嵌入模型'],
    ollama_id: '5de93a84837d',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'f34e6517-8213-4be2-871e-386535343432393331383939',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'Yi',
    method: '',
    desc: 'yi-coder-1.5B 是零一万物开源的 1.5 亿参数‌编程助手模型‌，支持52种编程语言‌‌，擅长代码生成、代码补全和调试任务‌。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'yi-coder:1.5b',
    service_provider_name: 'local_ollama_chat',
    size: '866MB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/yi.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '186c460ee707',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
  {
    id: 'd25e82de-95bc-4c0b-a507-626537626131336334623934',
    service_name: 'chat',
    api_flavor: 'ollama',
    flavor: 'Yi',
    method: '',
    desc: 'yi-coder-9B 是零一万物开源的90亿参数‌代码模型‌，支持52种编程语言‌‌，在代码生成、调试与补全任务中性能超越同规模模型，适用于复杂项目级开发‌。',
    url: '',
    auth_type: '',
    auth_apply_url: '',
    auth_fields: [''],
    name: 'yi-coder:9b',
    service_provider_name: 'local_ollama_chat',
    size: '5.0GB',
    is_recommended: false,
    status: '',
    avatar: 'http://120.232.136.73:31619/byzedev/model_avatar/yi.png',
    can_select: false,
    class: ['文本生成'],
    ollama_id: '39c63e7675d7',
    params_size: 0,
    input_length: 0,
    output_length: 0,
    source: 'local',
    smartvision_provider: '',
    smartvision_model_key: '',
    is_downloaded: false,
    think: false,
  },
];

export const availableMcps: IMcpListItem[] = [
  {
    id: '683ec88241fa614eb15323b9',
    name: {
      src: 'Jina-AI-MCP-Tools',
      zh: 'Jina-AI-MCP-Tools',
    },
    abstract: {
      src: 'A Model Context Protocol (MCP) server that integrates with Jina AI Search Foundation APIs.',
      zh: '一个与 Jina AI 搜索基础 API 集成的 模型上下文协议（MCP）服务器。',
    },
    supplier: 'PsychArch',
    logo: 'https://resources.modelscope.cn/mcp-server-cover/3981b5de-be7a-4134-9ced-488018601ebc.png',
    popularity: 44,
    tags: [],
    hosted: true,
    status: 0,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747836466,
  },
  {
    id: '683ec88241fa614eb1532449',
    name: {
      src: 'MCP-Advisor',
      zh: 'MCP-Advisor',
    },
    abstract: {
      src: 'MCP Advisor is a discovery and recommendation service that helps AI assistants explore Model Context Protocol (MCP) servers using natural language queries. It makes it easier for users to find and leverage MCP tools suitable for specific tasks.',
      zh: 'MCP Advisor 是一个发现和推荐服务，帮助 AI 助手使用自然语言查询探索 Model Context Protocol (MCP) 服务器。它让用户更容易找到并利用适合特定任务的 MCP 工具。',
    },
    supplier: 'istarwyh',
    logo: '',
    popularity: 35,
    tags: [],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829990,
  },
  {
    id: '683ec88241fa614eb1531fc5',
    name: {
      src: 'mcp-server-alipay',
      zh: '支付宝MCP',
    },
    abstract: {
      src: '@alipay/mcp-server-alipay 是支付宝开放平台提供的 MCP Server，让你可以轻松将支付宝开放平台提供的交易创建、查询、退款等能力集成到你的 LLM 应用中，并进一步创建具备支付能力的智能工具。',
      zh: '是支付宝开放平台提供的 MCP Server，让你可以轻松将支付宝开放平台提供的交易创建、查询、退款等能力集成到你的 LLM 应用中，并进一步创建具备支付能力的智能工具。',
    },
    supplier: 'alipay',
    logo: 'https://resources.modelscope.cn/studio-cover-prod/studio-cover_86796236-c604-4a77-bfa4-e9ca2ca93297.png',
    popularity: 24900,
    tags: ['支付工具'],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829985,
  },
  {
    id: '683ec88241fa614eb1531fd6',
    name: {
      src: 'leetcode-mcp-server',
      zh: 'LeetCode(力扣)',
    },
    abstract: {
      src: 'LeetCode MCP server implementation for LeetCode API integration, enabling automated access to programming problems, user data, and contest information.',
      zh: 'MCP 服务器实现 LeetCode API 集成，支持自动化获取编程题库、用户数据和竞赛信息。',
    },
    supplier: 'jinzcdev',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_402ed2b0-a575-4187-813f-ae82d89af6a1.png',
    popularity: 6685,
    tags: ['知识搜索'],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829983,
  },
  {
    id: '683ec88241fa614eb1531fc7',
    name: {
      src: 'bing-cn-mcp-server',
      zh: '必应搜索中文',
    },
    abstract: {
      src: 'Bing search Chinese',
      zh: '必应搜索中文',
    },
    supplier: 'yan5236',
    logo: 'https://resouces.modelscope.cn/studio-cover-prod/studio-cover_c1a4feec-7dd2-4188-bd72-aebde64758f3.png',
    popularity: 11337,
    tags: ['搜索服务'],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829976,
  },
  {
    id: '683ec88241fa614eb1531fc4',
    name: {
      src: 'amap-maps',
      zh: '高德地图',
    },
    abstract: {
      src: 'Amap Maps is a server that supports any MCP protocol client, allowing users to easily utilize the Amap Maps MCP server for various location-based services.',
      zh: '高德地图是一个支持任何MCP协议客户端的服务器，允许用户轻松利用高德地图MCP服务器获取各种基于位置的服务。',
    },
    supplier: 'amap',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_982efeea-b6fe-4c38-91da-501de5a7f098.png',
    popularity: 43332,
    tags: ['地图服务'],
    hosted: true,
    status: 1,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747829974,
  },
  {
    id: '683ec88241fa614eb1531fc3',
    name: {
      src: 'fetch',
      zh: 'Fetch网页内容抓取',
    },
    abstract: {
      src: 'This server enables LLMs to retrieve and process content from web pages, converting HTML to markdown for easier consumption.',
      zh: '该服务器使大型语言模型能够检索和处理网页内容，将HTML转换为markdown格式，以便于更轻松地使用。',
    },
    supplier: 'modelcontextprotocol',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_761f7bfe-fc5c-4753-b955-dcdd3288941b.png',
    popularity: 69492,
    tags: ['网页抓取'],
    hosted: true,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829971,
  },
  {
    id: '683ec88241fa614eb1532098',
    name: {
      src: 'sentry',
      zh: 'Sentry监控工具',
    },
    abstract: {
      src: 'This server provides tools to inspect error reports, stacktraces, and other debugging information from your Sentry account.',
      zh: '此服务器提供了用于查看来自您的 Sentry 账户的错误报告、堆栈跟踪和其他调试信息的工具。',
    },
    supplier: 'modelcontextprotocol',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_c1f05f51-704c-45c2-8091-444c8149c912.png',
    popularity: 360,
    tags: [],
    hosted: true,
    status: 0,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb153204d',
    name: {
      src: 'gdrive',
      zh: '谷歌云盘文件管理器',
    },
    abstract: {
      src: 'This MCP server integrates with Google Drive to allow listing, reading, and searching over files.',
      zh: '该MCP服务器与Google Drive集成，以允许列出、读取和搜索文件。',
    },
    supplier: 'modelcontextprotocol',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_bbbedf4b-06fa-4b63-a558-c00938e8ee65.png',
    popularity: 629,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb153203b',
    name: {
      src: 'mcp-server-neon',
      zh: 'Neon数据库',
    },
    abstract: {
      src: 'Lets you use Claude Desktop, or any MCP Client, to use natural language to accomplish things with [Neon](https://neon.tech/).',
      zh: '让你能够使用 Claude Desktop 或任何 MCP 客户端，通过自然语言来使用 [Neon](https://neon.tech/) 完成任务。',
    },
    supplier: 'neondatabase-labs',
    logo: 'https://resources.modelscope.cn/mcp-covers/avatar/neondatabase-labs.png',
    popularity: 715,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 1,
    envRequired: 1,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb1532034',
    name: {
      src: 'workers-mcp',
      zh: 'Cloudflare Workers MCP连接器',
    },
    abstract: {
      src: 'A package that connects Claude Desktop and other MCP clients to Cloudflare Workers, enabling custom functionality to be accessed via natural language through the Model Context Protocol.',
      zh: '一个将 Claude Desktop 和其他 MCP 客户端连接到 Cloudflare Workers 的软件包，通过模型上下文协议（Model Context Protocol）， enables 自定义功能可以通过自然语言访问。',
    },
    supplier: 'cloudflare',
    logo: 'https://resources.modelscope.cn/mcp-covers/avatar/cloudflare.png',
    popularity: 789,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829968,
  },
  {
    id: '683ec88241fa614eb153202b',
    name: {
      src: 'ableton-mcp',
      zh: 'Ableton',
    },
    abstract: {
      src: 'Connects Ableton Live to Claude AI through the Model Context Protocol, enabling AI-assisted music production by allowing Claude to directly interact with and control Ableton Live sessions.',
      zh: '通过模型上下文协议将Ableton Live与Claude AI连接起来，通过允许Claude直接与Ableton Live会话交互和控制，实现人工智能辅助的音乐制作。',
    },
    supplier: 'ahujasid',
    logo: 'https://resources.modelscope.cn/studio-cover-pre/studio-cover_4f162c8b-eb82-4634-9d86-61981b735e3c.jpg',
    popularity: 893,
    tags: [],
    hosted: false,
    status: 1,
    authorized: 0,
    envRequired: 0,
    updatedAt: 1747829968,
  },
];
